# Generated by cpp11: do not edit by hand

raw_compression <- function(src, level) {
  .Call(`_zstd_raw_compression`, src, level)
}

decompression <- function(src) {
  .Call(`_zstd_decompression`, src)
}

stream_compression_ <- function(src, dest, level, cores) {
  invisible(.Call(`_zstd_stream_compression_`, src, dest, level, cores))
}

stream_decompression <- function(src, dest) {
  invisible(.Call(`_zstd_stream_decompression`, src, dest))
}
