# Generated by cpp11: do not edit by hand

compression_ <- function(src, level) {
  .Call(`_zstd_compression_`, src, level)
}

decompression_ <- function(src) {
  .Call(`_zstd_decompression_`, src)
}

stream_compression_ <- function(src, dest, level, cores) {
  invisible(.Call(`_zstd_stream_compression_`, src, dest, level, cores))
}

stream_decompression_ <- function(src, dest) {
  invisible(.Call(`_zstd_stream_decompression_`, src, dest))
}
