# Generated by cpp11: do not edit by hand

compress_raw_ <- function(src, level) {
  .Call(`_zstd_compress_raw_`, src, level)
}

decompress_raw_ <- function(src) {
  .Call(`_zstd_decompress_raw_`, src)
}

compress_connection_ <- function(src, dest, level, cores) {
  invisible(.Call(`_zstd_compress_connection_`, src, dest, level, cores))
}

decompress_connection_ <- function(src, dest) {
  invisible(.Call(`_zstd_decompress_connection_`, src, dest))
}
